settings:
  title: 'Status Page'
  url: 'https://status.earmer.top' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-earmer-top # unique identifier
    name: www.earmer.top
    description: 'Earmer Blog on VPS' # default=empty
    url: 'https://www.earmer.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: blog-earmer-top
    name: blog.earmer.top
    description: 'Earmer Blog on Github Page (Stop Update)'
    url: 'https://blog.earmer.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: talk-earmer-top
    name: talk.earmer.top
    description: 'A BBS With Material'
    url: 'https://talk.earmer.top'
    method: GET
    expectStatus: 200
    
  - id: bt-earmer-top
    name: bt.earmer.top
    url: 'https://bt.earmer.top'
    methos: GET
    expectStatus: 404
